# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/personaldb
spring.datasource.username=postgres
spring.datasource.password=1512
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

#Jwt Token
jwt.secret=3f5a9b8c1d2e4f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0i
jwt.expiration=86400000